name: Build WF
on:
  push:
    branches:
     - main

#  pull_requests:
#    branches:
#      - main

  workflow_dispatch:

  schedule:
    - cron: "10 14 * * 1-5" # After noon 2:10pm, Monday to Friday
  
permissions:
   contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      -  name: Code checkout
         uses: actions/checkout@v4
         with:
           fetch-depth: 0

      - name: Maven Build
        run: mvn install
      
      - name: Upload Build Artifact (WAR)
        uses: actions/upload-artifacts@v4
        with:
          name: vprofile-app
          path: target/*.war

      - name: Notify if Builds Fails
        if: failure()
        run: echo "build job failed! Please check logs."
  
  
  Testing:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      -  name: Code checkout
         uses: actions/checkout@v4
         with:
           fetch-depth: 0

      - name: Run tests on main branch
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle
   